name = "New_package"
uuid = "05af9cfc-0cc3-4040-99aa-eeb3a3c38898"
authors = ["Vivan Sharma <vivan.sharma@sciencespo.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
